version: '3.6'
services:
  web:
    build: ./api/flask/
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
  mysql:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword