homeassistant:
  # Name of the location where Home Assistant is running
  name: 我爱我家
  # Location required to calculate the time the sun rises and sets
  latitude: 30.6667
  longitude: 104.0667
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
    api_password: !secret http_password
  
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: time_date
    display_options:
      - 'time'
#      - 'date'
#      - 'date_time'
#      - 'time_date'
      - 'time_utc'
#      - 'beat'
#  - platform: worldclock
#    time_zone: Asia/Shanghai

    #空气质量
  - platform: airvisual
    api_key: !secret sensor_api_key
    monitored_conditions:
#      - us
      - cn
    latitude: 30.5579049682
    longitude: 104.0336877108
    radius: 500
#  - platform: fitbit
#    clock_format: 12H
#    monitored_resources:
#      - "body/weight"
  - platform: dnsip


# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#雅虎天气
weather:
  - platform: yweather
    woeid: 2158433
    name: Chengdu
    
# 小米网关
xiaomi_aqara:
  gateways:
    - mac:
      key: !secret xiaomi_aqara_key
# 小米扫地机器人
vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip
    token: !secret vacuum_token
    name: miRoboot
#小米遥控器 
switch:
  - platform: chuangmi_ir
    name: "Living Room IR Remote"
    host: !secret switch_host
    token: !secret switch_token
    switches:
      reciever:
        command_on: 'Z6VHACoCAACPBgAAuAgAAIMRAAA3IwAAmJ4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAQEBAQEBAQEAAAAAAAABAAEBAQEBAQABBQJAA='
        command_off: 'Z6VHACoCAACPBgAAuAgAAIMRAAA3IwAAmJ4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAQEBAQEBAQEAAAAAAAABAAEBAQEBAQABBQJAA='
  - platform: rpi_gpio
    ports:
      14: Fan Office 
    
#语音
#media_player :
#  - platform: vlc
#    name: VLCplayer 
  
# 语音朗读
#tts:
#  - platform: google
tts:
  - platform: baidu
    app_id: !secret tts_app_id
    api_key: !secret tts_app_key
    secret_key: !secret tts_app_secret_key
    #语速，取值0-9，默认为5中语速
    speed: 5 
    #音调，取值0-9，默认为5中语调
    pitch: 5
    #音量，取值0-15，默认为5中音量
    volume: 6
    #发音人选择, 0为女声，1为男声，3为情感合成-度逍遥，4为情感合成-度丫丫，默认为0
    person: 0
frontend:
  themes:
    night: #主题名称，英文
    # 主界面 #
      primary-color: "#1DE9B6" # 主 UI 字体颜色
      primary-background-color: "#303030" # 其他部件背景色 (dialogs, e.t.c)
      secondary-background-color: "#303030" # 主 UI 背景颜色
      paper-card-background-color: "#424242" # 卡片背景颜色
      paper-item-icon-color: "#1DE9B6" # Icon colour
      primary-text-color: "#FFFFFF" # 首选字体颜色
      secondary-text-color: "rgba(255, 255, 255, 0.7)" # 次字体颜色
      disabled-text-color: "rgba(255, 255, 255, 0.5)" # Disabled text colour
      divider-color: "rgba(255, 255, 255, 0.12)" # Divider colour
      paper-card-header-color: "#FFFFFF" # 卡片标题颜色
      # 侧边栏 #
      paper-listbox-background-color: "#424242" # 背景色
      paper-listbox-color: "#FFFFFF" # 字体色
      paper-grey-200: "#616161" # 选中项背景色
      # 开关 #
      paper-toggle-button-checked-ink-color: "#1DE9B6"
      paper-toggle-button-checked-button-color: "#1DE9B6"
      paper-toggle-button-checked-bar-color: "#1DE9B6"
      # Sliders #
      paper-slider-knob-color: "#1DE9B6"
      paper-slider-knob-start-color: "#1DE9B6"
      paper-slider-pin-color: "#1DE9B6"
      paper-slider-active-color: "#1DE9B6"
      paper-slider-secondary-color: "#33F2D8"
    solarized:
      primary-color: "#2aa198"
      disabled-text-color: "#859900"
      divider-color: "#586e75" #"rgba(255, 255, 255, 0.12)"
      paper-card-background-color: "#002b36"
      paper-grey-200: "#586e75"
      paper-item-icon-color: "#b58900"
      paper-listbox-background-color: "#002b36"
      paper-listbox-color: "#b58900"
      primary-background-color: "#073642"
      primary-text-color: "#839496"
      secondary-background-color: "#073642"
      secondary-text-color: "#859900"
      text-primary-color: "#839496"
      label-badge-background-color: "var(--secondary-background-color)"
      label-badge-text-color: "var(--text-primary-color)"
      paper-card-header-color: "#cb4b16"
      paper-grey-50: "#b58900"
      paper-item-icon-active-color: "#dc322f"
      paper-item-icon_-_color: "#FF00FF"   # no clue 
      paper-slider-active-color: "#dc322f"
      paper-slider-knob-color: "#dc322f"
      paper-slider-knob-start-color: "#b58900"
      paper-slider-pin-color: "#FF00FF"  # no clue
      paper-slider-secondary-color: "#dc322f"
      paper-toggle-button-checked-ink-color: "#dc322f"
      paper-toggle-button-checked-button-color: "#dc322f"
      paper-toggle-button-checked-bar-color: "#cb4b16"
      paper-toggle-button-unchecked-bar-color: "#b58900"
      table-row-background-color: "#002b36"
      table-row-alternative-background-color: "#073642"
      google-red: "#dc322f"
      google-green: "#859900"
      google-blue: "#268bd2"
      google-yellow: "#b58900"
      accent-color: "#cb4b16"
      paper-green: "#859900"
      paper-blue: "#268bd2"
      paper-orange: "#cb4b16"
    PmxMononight:
      # MyVariables
      base-hue: '220' #Controls the base (and accent) color hue (0-360) | 0=Red 60=Yellow 120=Green 180=Cyan 240=Blue 300=Magenta 360=Red
      base-sat: '16%' #Controls the saturation of the theme (0%-100%) | 0%=Grey 100%=Full Saturation
      # MyVar
      huesat: 'var(--base-hue), var(--base-sat),'
      # Primary Color
      primary-color: 'hsl(var(--huesat) 20%)'
      # Backgrounds
      primary-background-color: 'var(--primary-color)'
      secondary-background-color: 'hsl(var(--huesat) 16%)'
      paper-listbox-background-color: 'var(--primary-color)'
      paper-card-background-color: 'hsl(var(--huesat) 12%)'
      paper-dialog-background-color: 'var(--paper-card-background-color)'
      table-row-background-color: 'hsl(var(--huesat) 12%)'
      table-row-alternative-background-color: 'hsl(var(--huesat) 10%)'
      # Devider
      divider-color: 'hsla(0, 0%, 0%, 0)'
      dark-divider-opacity: '0'
      light-divider-opacity: '0'
      # Text colors
      primary-text-color: 'hsl(var(--huesat) 60%)'
      text-primary-color: 'hsl(var(--huesat) 60%)'
      secondary-text-color: 'hsl(var(--huesat) 60%)'
      disabled-text-color: 'hsl(var(--huesat) 70%)'
      sidebar-text_-_color: 'hsl(var(--huesat) 90%)'
      sidebar-text-color: 'hsl(var(--huesat) 90%)'
      paper-card-header-color: 'hsl(var(--base-hue), 90%, 50%)'
      # Text Adjustments
      paper-font-headline_-_letter-spacing: '-0.5px'
      paper-font-headline_-_font-weight: '500'
      paper-font-body1_-_font-weight: '500'
      # Nav Menu
      paper-listbox-color: 'hsl(var(--huesat) 50%)'
      paper-grey-50: 'hsl(var(--huesat) 50%)'
      paper-grey-200: 'hsla(var(--huesat) 26%)'
      # Paper card
      paper-item-icon-color: 'hsl(var(--huesat) 30%)'
      paper-item-icon-active-color: 'var(--paper-item-icon-color)'
      paper-item-icon_-_color: 'var(--paper-item-icon-color)'
      paper-item-selected_-_background-color: 'hsla(0, 0%, 0%, 0.2)'
      paper-tabs-selection-bar-color: 'hsla(0, 0%, 0%, 0.2)'
      # Labels
      label-badge-red: 'hsla(0, 0%, 0%, 0)'
      label-badge-border-color: 'var(--label-badge-red)'
      label-badge-background-color: 'var(--paper-card-background-color)'
      label-badge-text-color: 'var(--primary-text-color)'
      # Shadows
      shadow-elevation-2dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 18%)'
      shadow-elevation-16dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 28%)'
      # Switches
      paper-toggle-button-checked-button-color: 'hsl(var(--base-hue), 90%, 50%)'
      paper-toggle-button-checked-bar-color: 'hsl(var(--huesat) 25%)'
      paper-toggle-button-unchecked-button-color: 'hsl(var(--huesat) 25%)'
      paper-toggle-button-unchecked-bar-color: 'hsl(var(--huesat) 5%)'
      # Sliders
      paper-slider-knob-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-knob-start-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-slider-pin-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-active-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-container-color: 'hsl(var(--huesat) 28%)'
      paper-slider-secondary-color: 'hsl(var(--huesat) 90%)'
      paper-slider-disabled-active-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-slider-disabled-secondary-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-dialog-color: 'hsl(var(--base-hue), 20%, 80%)'